print "Welcome to the Survay!"
name1 = raw_input("First participant, What is your name? ")
name2 = raw_input("Second participant, What is your name? ")
color1 = raw_input("%s, what is your favorite color? " % (name1))
color2 = raw_input("%s, what is your favorite color? " % (name2))
hobby1 = raw_input("%s, what is your favorite hobby? " % (name1))
hobby2 = raw_input("%s, what is your favorite hobby? " % (name2))
movie1 = raw_input("%s, what is your favorite movie? " % (name1))
movie2 = raw_input("%s, what is your favorite movie? " % (name2))
book1 = raw_input("%s, what is your favorite book? " % (name1))
book2 = raw_input("%s, what is your favorite book? " % (name2))
song1 = raw_input("%s, what is your favorite song? " % (name1))
song2 = raw_input("%s, what is your favorite song? " % (name2))

print "%s's favorite color is %s" % (name1, color1)
print "%s's favorite color is %s" % (name2, color2)
print "%s's favorite hobby is %s" % (name1, hobby1)
print "%s's favorite hobby is %s" % (name2, hobby2)
print "%s's favorite movie is %s" % (name1, movie1)
print "%s's favorite movie is %s" % (name2, movie2)
print "%s's favorite book is %s" % (name1, book1)
print "%s's favorite book is %s" % (name2, book2)
print "%s's favorite song is %s" % (name1, song1)
print "%s's favorite song is %s" % (name2, song2)